name = "lean-cutting-planes"
version = "0.1.0"
defaultTargets = ["lean-cutting-planes"]

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "LeanCuttingPlanes"

[[lean_exe]]
name = "lean-cutting-planes"
root = "Main"
