name: Lean Action CI

on:
  push:
    paths:
      - 'LeanCuttingPlanes/**'
  pull_request:
    paths:
      - 'LeanCuttingPlanes/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: leanprover/lean-action@v1
